### ISSUE TITLE
Recorded File not Playing

### ISSUE THREAD

**Issue by ngov94** [neharikapurieng/TalkBox#1]
**OS:** Linux
**Java Version:** 1.8.0_181
**Description:**  The recorded files cannot be played after being added to the button in the TalkBox Preview.
**Steps to Reproduce:**
    1. Enter the number of buttons.
    2. Enter the profile name and select profile from the list.
    3. Enter the name for the recorded file.
    4. Press the “Record” button.
    5. Record the audio.
    6. Press stop.
    7. Select the recorded file from the Audio list.
    8. Press “Add Sound” button.
    9. Select the profile from the list and press the “Set Profile” button.
    10. Press the recorded audio button in the TalkBox Preview.
**Actual vs Expected Results:**
Expected Result:
The recorded audio is played.
Actual Result:
The audio is not played. In the terminal, it will give the following error:
_Can't find audio file: message = Audio clip path does not exist 
Path used:TalkBoxConfigurator/Audio/test1.wav_
![image](https://user-images.githubusercontent.com/43424296/54140734-aa539480-43fa-11e9-9d4a-12d3a47aba71.png)

**Comment by neharikapurieng** [comment]
The bug is now fixed before the file was not playing the recorded audio, but now I have fixed it so that it saves that audio and plays it.
